// Mocks generated by Mockito 5.4.6 from annotations
// in krono/test/src/core/utils/backup_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:krono/src/core/utils/thumbnail/thumbnail_service.dart' as _i5;
import 'package:krono/src/features/journal/data/journal_repository.dart' as _i2;
import 'package:krono/src/features/journal/data/models/journal_entry.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [JournalRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockJournalRepository extends _i1.Mock implements _i2.JournalRepository {
  MockJournalRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> addEntry(
    _i4.JournalEntry? entry,
    String? tempPath, {
    bool? deleteSource = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addEntry,
          [
            entry,
            tempPath,
          ],
          {#deleteSource: deleteSource},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateEntry(
    _i4.JournalEntry? entry, {
    String? newTempPath,
    bool? deleteSource = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEntry,
          [entry],
          {
            #newTempPath: newTempPath,
            #deleteSource: deleteSource,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteEntry(_i4.JournalEntry? entry) => (super.noSuchMethod(
        Invocation.method(
          #deleteEntry,
          [entry],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.JournalEntry>> getAllEntries() => (super.noSuchMethod(
        Invocation.method(
          #getAllEntries,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.JournalEntry>>.value(<_i4.JournalEntry>[]),
      ) as _i3.Future<List<_i4.JournalEntry>>);

  @override
  _i3.Future<void> deleteAllData() => (super.noSuchMethod(
        Invocation.method(
          #deleteAllData,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [ThumbnailService].
///
/// See the documentation for Mockito's code generation for more information.
class MockThumbnailService extends _i1.Mock implements _i5.ThumbnailService {
  MockThumbnailService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String?> generateThumbnail(
    String? originalPath, {
    int? width = 300,
    int? quality = 85,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateThumbnail,
          [originalPath],
          {
            #width: width,
            #quality: quality,
          },
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);
}
