import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'models/streak_adjustment_type.dart';
import 'tables/activity_log.dart';
import 'tables/day_entries.dart';
import 'tables/streak_adjustments.dart';

part 'database.g.dart';

/// Provides a singleton instance of the [AppDatabase] for the application.
///
/// The database connection is automatically closed when the provider is disposed.
final databaseProvider = Provider<AppDatabase>((ref) {
  final db = AppDatabase();
  ref.onDispose(() => db.close());
  return db;
});

/// The primary database engine for the Krono application.
///
/// Handles schema versioning, migrations, and provides access to all tables
/// through Data Access Objects (DAOs) generated by Drift.
@DriftDatabase(tables: [DayEntries, StreakAdjustments, ActivityLog])
class AppDatabase extends _$AppDatabase {
  /// Initializes the database with a platform-optimized connection.
  AppDatabase() : super(_openConnection());

  AppDatabase.forTesting(super.e);

  /// The current version of the database schema.
  ///
  /// This must be incremented each time the table structure is modified.
  @override
  int get schemaVersion => 5;

  /// Defines the migration strategy for handling schema changes between versions.
  @override
  MigrationStrategy get migration {
    return MigrationStrategy(
      onCreate: (m) async {
        await m.createAll();
      },
      onUpgrade: (m, from, to) async {
        // Each "if" block handles a sequential schema upgrade.
        if (from < 2) {
          // Migration from v1 to v2: Added location and weather support.
          await m.addColumn(dayEntries, dayEntries.location);
          await m.addColumn(dayEntries, dayEntries.weatherTemp);
          await m.addColumn(dayEntries, dayEntries.weatherIcon);
        }
        if (from < 3) {
          // Migration from v2 to v3: Added thumbnail support for grid performance.
          await m.addColumn(dayEntries, dayEntries.thumbnailPath);
        }
        if (from < 4) {
          // Migration from v3 to v4: Added streak adjustments for monetization/restores.
          await m.createTable(streakAdjustments);
        }
        if (from < 5) {
          // Migration from v4 to v5: Added a dedicated log for completed activities.
          await m.createTable(activityLog);
        }
      },
      beforeOpen: (details) async {
        // This callback is executed before any queries are sent.
        // Useful for enabling features like foreign keys if needed.
      },
    );
  }

  /// Creates the platform-specific database connection.
  static QueryExecutor _openConnection() {
    return driftDatabase(
      name: 'krono_database',
      native: const DriftNativeOptions(
        // Allows the database connection to be used across different isolates,
        // which is beneficial for background processing.
        shareAcrossIsolates: true,
      ),
    );
  }
}